version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=1000
        - PGID=1000
        - INSTALL_XDEBUG=true
    environment:
      PHP_IDE_CONFIG: "serverName=$${serverName}"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  mysql:
    image: mysql
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: $${PMA_HOST}
      PMA_USER: $${PMA_USER}
      PMA_PASSWORD: $${PMA_PASSWORD}
    ports:
      - "8088:80"
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - HOSTNAME_EXTERNAL=localhost
      - services=s3,ses
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=$${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=$${AWS_SECRET_ACCESS_KEY}
    volumes:
      - "localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        aliases:
          - localhost.localstack.cloud
volumes:
  db_data:
  localstack-data: